/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/

var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}
 


    
  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);



//call back function for YGL
 var callbackFunction = function(data) {
    var item = data.query.results.channel.item;
    var cond = item.condition; 
    var fore = item.forecast;      
    today(cond.temp, cond.date, cond.text, cond.code);
    day1(fore[1].low, fore[1].high, fore[1].date,  fore[1].code  );
    day2(fore[2].low, fore[2].high, fore[2].date,  fore[2].code  );
    day3(fore[3].low, fore[3].high, fore[3].date,  fore[3].code  );  
    
  };


var tempC = function(f) {
    return Math.round((f-32.0)*5.0/9.0);
 };

$('#dropdown li').on('click', function(){
$('button').replaceWith('<button class=\"btn btn-default btn-lg dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\"  aria-expanded=\"false\">'+ $(this).text() + '<span class=\"caret\"></span></button>');
var yql = "http://query.yahooapis.com/v1/public/yql?q=select item from weather.forecast where woeid in (select woeid from geo.places(1) where text='"+$(this).text()+"')&format=json";

$.getJSON(yql,callbackFunction);

});



var setSkycons  = function(canvasid,yahoocode) {
  switch(yahoocode) {
    case "1": 
        skycons.set(canvasid, Skycons.SLEET);
        break;
    case "3":
        skycons.set(canvasid, Skycons.SLEET);
        break;
    case "4":
        skycons.set(canvasid, Skycons.SLEET);
        break;        
    case "9":
        skycons.set(canvasid, Skycons.RAIN);
        break;       
    case "11":
        skycons.set(canvasid, Skycons.RAIN);
        break;        
    case "12":
        skycons.set(canvasid, Skycons.RAIN);
        break;        
    case "18":
        skycons.set(canvasid, Skycons.SLEET);
        break;        
    case "19":
        skycons.set(canvasid, Skycons.FOG);
        break;        
    case "20":
        skycons.set(canvasid, Skycons.FOG);
        break;       
    case "21":
        skycons.set(canvasid, Skycons.FOG);
        break;       
    case "22":
        skycons.set(canvasid, Skycons.FOG);
        break;       
    case "23":
        skycons.set(canvasid, Skycons.FOG);
        break;               
    case "24":
        skycons.set(canvasid, Skycons.WIND);
        break;         
    case "25":
        skycons.set(canvasid, Skycons.WIND);
        break;               
    case "26":
        skycons.set(canvasid, Skycons.CLOUDY);
        break;               
    case "27":
        skycons.set(canvasid, Skycons.CLOUDY);
        break;               
    case "28":
        skycons.set(canvasid, Skycons.CLOUDY);
        break;               
    case "29":
        skycons.set(canvasid, Skycons.PARTLY_CLOUDY_NIGHT);
        break;               
    case "30":
        skycons.set(canvasid, Skycons.PARTLY_CLOUDY_DAY);
        break;      
    case "31":
        skycons.set(canvasid, Skycons.CLEAR_NIGHT);
        break;              
    case "32":
        skycons.set(canvasid, Skycons.CLEAR_DAY);
        break;              
    case "33":
        skycons.set(canvasid, Skycons.CLEAR_NIGHT);
        break;              
    case "34":
        skycons.set(canvasid, Skycons.CLEAR_DAY);
        break;              
    case "35":
        skycons.set(canvasid, Skycons.RAIN);
        break;              
    case "36":
        skycons.set(canvasid, Skycons.CLEAR_DAY);
        break;              
    case "37":
        skycons.set(canvasid, Skycons.RAIN);
        break;              
    case "38":
        skycons.set(canvasid, Skycons.RAIN);
        break;              
    case "39": 
        skycons.set(canvasid, Skycons.RAIN);
        break;              
    case "40":
        skycons.set(canvasid, Skycons.RAIN);
        break;              
    case "44":
        skycons.set(canvasid, Skycons.CLOUDY);
        break;              
    case "45":
        skycons.set(canvasid, Skycons.RAIN);
        break;             
    case "47":
        skycons.set(canvasid, Skycons.RAIN);
        break;                      
    default:
        skycons.set(canvasid, Skycons.CLEAR_DAY);
  };    
};


var today = function(temperature_now, today, weather, yahoocode  ){

$('.temperature').text(tempC(temperature_now));
                                                          
$('.condition').replaceWith('<div class="condition"><span class="date">'+ today+ '</span> : '+ weather+ '</div>');                                                          
setSkycons("today",yahoocode);                              

};



var day1 = function(tempL, tempH, day,  yahoocode ){
  $('th').each( function (index) {
     if (index === 0) {$(this).text(day)}
     });
  $('td').each( function (index) {
     if (index===0) { $(this).replaceWith('<td>'+tempC(tempL)+'-'+tempC(tempH)+' &#8451;</td>');}  
    });
  setSkycons("day1",yahoocode);                              
};



var day2 = function(tempL, tempH, day,  yahoocode ){
  $('th').each( function (index) {
     if (index === 1) {$(this).text(day)}
     });
  $('td').each( function (index) {
     if (index===1) { $(this).replaceWith('<td>'+tempC(tempL)+'-'+tempC(tempH)+' &#8451;</td>');}  
    });
  setSkycons("day2",yahoocode);                              
};


var day3 = function(tempL, tempH, day,  yahoocode ){
  $('th').each( function (index) {
     if (index === 2) {$(this).text(day)}
     });
  $('td').each( function (index) {
     if (index===2) { $(this).replaceWith('<td>'+tempC(tempL)+'-'+tempC(tempH)+' &#8451;</td>');}  
    });
  setSkycons("day3",yahoocode);                       
};  



  




